### ISSUE TITLE
no HPD_modality attribute causes a continuous trait analysis of MCC tree to fail

### ISSUE THREAD

**Issue by SimonGreenhill** [phylogeography/SpreaD3#27]
If there is no <trait>_%HPD_modality attribute on the tree, then the SpreaD3 gui raises an error:

```
setSelectedIndex: 0 out of bounds
```

STDOUT shows the real error:

```
locationsgeo_%HPD_modality attribute could not be found on the internal node. Resulting visualisation may be incomplete!
```

... and yes, the visualisation is incomplete (no HPD ranges). 

The [Spherical Diffusion phylogeography package](https://peerj.com/articles/2406/) for BEAST2 doesn't seem to log this attribute, and the HPD info is in locationsgeo{1,2}_95%_HPD={..}. 

Perhaps the GUI should display a more helpful error message (like the one in STDOUT).

Does the BEAST2 package need to log the modality for SpreaD3 to work?

**Comment by GuyBaele** [comment]
@SimonGreenhill Can you send me the file you were trying to load into SpreaD3 so that I can try to reproduce the problem and debug? Thanks!

**Comment by GuyBaele** [comment]
This is the same issue as posted on the BEAST user list:
https://groups.google.com/forum/#!topic/beast-users/sl98sz4mVRU

I'm not getting the 'setSelectedIndex: 0 out of bounds' error message though when I load the MCC file that Kalene shared on the user list, as SpreaD3 tells me that there are 'No matching HPD_modality attributes found for selected coordinate attributes', which accurately reflects the problem.

**Comment by SimonGreenhill** [comment]
That looks and sounds exactly like it. Are you happy with the tree from that mailing list post, or want me to send my one too?

**Comment by GuyBaele** [comment]
This has been fixed in the source code but no new jar file had been released yet.
I'm putting a new build onto our lab's website, but note that it has not yet been thoroughly tested:
https://rega.kuleuven.be/cev/ecv/software/SpreaD3

**Comment by SimonGreenhill** [comment]
Just confirming, that this RC now generates the correct warning. 

The underlying problem seems to come from treeannotator in the beast2 package not including HPD_modality annotations, I will follow up with beast2 developers.

**Comment by GuyBaele** [comment]
Is it possible to run a BEAST2 .trees file through TreeAnnotator of the BEAST 1 package?

**Comment by SimonGreenhill** [comment]
Yes, that works.
